### ISSUE TITLE
Getting a 404- Not Found page.

### ISSUE THREAD

**Issue by grshankersai** [omoponfhir/omoponfhir-r4-server#5]
Hello,
I followed all the instructions to set up the omoponfhir project. But when I run it using docker, I am getting the 404-Not Found error page. Tried to resolve it in many ways, but not able to figure out where I am going wrong
Can someone kindly help me resolve it?

**Comment by myungchoi** [comment]
> Hello,
> I followed all the instructions to set up the omoponfhir project. But when I run it using docker, I am getting the 404-Not Found error page. Tried to resolve it in many ways, but not able to figure out where I am going wrong
> Can someone kindly help me resolve it?

What's the URL you used?  If you used the docker, http://localhost:8080/{name of warfile}/ for the tester UI. And, http://localhost:8080/{name of warfile}/fhir for the FHIR API url.

**Comment by kmdauwa** [comment]
Hello,

I am getting the same error after running it using docker. I checked the logs in the docker container of that image, and inside the localhost log file these are the first couple of lines I see:

04-Apr-2024 18:04:11.704 INFO [main] org.apache.catalina.core.ApplicationContext.log No Spring WebApplicationInitializer types detected on classpath
04-Apr-2024 18:04:11.711 INFO [main] org.apache.catalina.core.ApplicationContext.log Initializing Spring root WebApplicationContext
04-Apr-2024 18:04:11.718 SEVERE [main] org.apache.catalina.core.StandardContext.listenerStart Exception sending context initialized event to listener instance of class [org.springframework.web.context.ContextLoaderListener]

Any idea what is causing this?

Thank you!

**Comment by myungchoi** [comment]
omoponfhir-r4-server needs another components to be compiled as well. Are
you just trying to build and use it? Or, do you want to work on the
implementation?

**Comment by kmdauwa** [comment]
The goal is to implement our own OMOPonFHIR server. For testing I was working with the Student-Demo, and mostly everything on the DB side looks fine. I am using the omoponfhir-main-v54-r4 as the main repo and running the docker build command to build an image. From there my idea is to use that server image and the DB image from the student-demo with the appropriate environment variables to docker-compose the whole thing. 
Is this approach okay?


In the logs of the server container I see these errors:


04-Apr-2024 19:05:24.795 INFO [main] org.apache.catalina.core.ApplicationContext.log No Spring WebApplicationInitializer types detected on classpath
04-Apr-2024 19:05:24.801 INFO [main] org.apache.catalina.core.ApplicationContext.log Initializing Spring root WebApplicationContext
04-Apr-2024 19:05:24.880 SEVERE [main] org.apache.catalina.core.StandardContext.listenerStart Exception sending context initialized event to listener instance of class [org.springframework.web.context.ContextLoaderListener]
	java.lang.NoSuchMethodError: 'java.lang.ClassLoader[] org.apache.logging.log4j.util.LoaderUtil.getClassLoaders()'
		at org.apache.logging.log4j.core.util.WatchManager.getEventServices(WatchManager.java:160)
		at org.apache.logging.log4j.core.util.WatchManager.<init>(WatchManager.java:137)
		at org.apache.logging.log4j.core.config.AbstractConfiguration.<init>(AbstractConfiguration.java:140)
		at org.apache.logging.log4j.core.config.NullConfiguration.<init>(NullConfiguration.java:32)
		at org.apache.logging.log4j.core.LoggerContext.<clinit>(LoggerContext.java:85)
		at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.createContext(ClassLoaderContextSelector.java:254)
		at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.locateContext(ClassLoaderContextSelector.java:218)
		at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.getContext(ClassLoaderContextSelector.java:136)
		at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.getContext(ClassLoaderContextSelector.java:123)
		at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.getContext(ClassLoaderContextSelector.java:117)
		at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:150)
		at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:47)
		at org.apache.logging.log4j.LogManager.getContext(LogManager.java:196)
		at org.apache.commons.logging.LogAdapter$Log4jLog.<clinit>(LogAdapter.java:146)
		at org.apache.commons.logging.LogAdapter$Log4jAdapter.createLog(LogAdapter.java:113)
		at org.apache.commons.logging.LogAdapter.createLog(LogAdapter.java:95)
		at org.apache.commons.logging.LogFactory.getLog(LogFactory.java:67)
		at org.apache.commons.logging.LogFactory.getLog(LogFactory.java:59)
		at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:253)
		at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:102)
		at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4452)
		at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:4890)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:171)
		at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:683)
		at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:658)
		at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:712)
		at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:969)
		at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1911)
		at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
		at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
		at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
		at java.base/java.util.concurrent.AbstractExecutorService.submit(Unknown Source)
		at org.apache.catalina.startup.HostConfig.deployWARs(HostConfig.java:771)
		at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:423)
		at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1629)
		at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:303)
		at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:114)
		at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:402)
		at org.apache.catalina.util.LifecycleBase.setState(LifecycleBase.java:345)
		at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:893)
		at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:845)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:171)
		at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1332)
		at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1322)
		at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
		at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
		at java.base/java.util.concurrent.AbstractExecutorService.submit(Unknown Source)
		at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:866)
		at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:240)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:171)
		at org.apache.catalina.core.StandardService.startInternal(StandardService.java:433)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:171)
		at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:921)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:171)
		at org.apache.catalina.startup.Catalina.start(Catalina.java:757)
		at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
		at java.base/java.lang.reflect.Method.invoke(Unknown Source)
		at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:345)
		at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:473)
04-Apr-2024 19:05:24.905 INFO [main] org.apache.catalina.core.ApplicationContext.log Closing Spring root WebApplicationContext
04-Apr-2024 19:05:24.906 SEVERE [main] org.apache.catalina.core.StandardContext.listenerStop Exception sending context destroyed event to listener instance of class [org.springframework.web.context.ContextLoaderListener]
	java.lang.NoClassDefFoundError: Could not initialize class org.apache.commons.logging.LogAdapter$Log4jLog
		at org.apache.commons.logging.LogAdapter$Log4jAdapter.createLog(LogAdapter.java:113)
		at org.apache.commons.logging.LogAdapter.createLog(LogAdapter.java:95)
		at org.apache.commons.logging.LogFactory.getLog(LogFactory.java:67)
		at org.apache.commons.logging.LogFactory.getLog(LogFactory.java:59)
		at org.springframework.web.context.ContextCleanupListener.<clinit>(ContextCleanupListener.java:43)
		at org.springframework.web.context.ContextLoaderListener.contextDestroyed(ContextLoaderListener.java:112)
		at org.apache.catalina.core.StandardContext.listenerStop(StandardContext.java:4498)
		at org.apache.catalina.core.StandardContext.stopInternal(StandardContext.java:5123)
		at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:242)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:175)
		at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:683)
		at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:658)
		at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:712)
		at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:969)
		at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1911)
		at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
		at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
		at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
		at java.base/java.util.concurrent.AbstractExecutorService.submit(Unknown Source)
		at org.apache.catalina.startup.HostConfig.deployWARs(HostConfig.java:771)
		at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:423)
		at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1629)
		at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:303)
		at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:114)
		at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:402)
		at org.apache.catalina.util.LifecycleBase.setState(LifecycleBase.java:345)
		at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:893)
		at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:845)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:171)
		at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1332)
		at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1322)
		at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
		at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
		at java.base/java.util.concurrent.AbstractExecutorService.submit(Unknown Source)
		at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:866)
		at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:240)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:171)
		at org.apache.catalina.core.StandardService.startInternal(StandardService.java:433)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:171)
		at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:921)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:171)
		at org.apache.catalina.startup.Catalina.start(Catalina.java:757)
		at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
		at java.base/java.lang.reflect.Method.invoke(Unknown Source)
		at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:345)
		at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:473)
	Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NoSuchMethodError: 'java.lang.ClassLoader[] org.apache.logging.log4j.util.LoaderUtil.getClassLoaders()' [in thread "main"]
		at org.apache.logging.log4j.core.util.WatchManager.getEventServices(WatchManager.java:160)
		at org.apache.logging.log4j.core.util.WatchManager.<init>(WatchManager.java:137)
		at org.apache.logging.log4j.core.config.AbstractConfiguration.<init>(AbstractConfiguration.java:140)
		at org.apache.logging.log4j.core.config.NullConfiguration.<init>(NullConfiguration.java:32)
		at org.apache.logging.log4j.core.LoggerContext.<clinit>(LoggerContext.java:85)
		at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.createContext(ClassLoaderContextSelector.java:254)
		at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.locateContext(ClassLoaderContextSelector.java:218)
		at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.getContext(ClassLoaderContextSelector.java:136)
		at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.getContext(ClassLoaderContextSelector.java:123)
		at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.getContext(ClassLoaderContextSelector.java:117)
		at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:150)
		at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:47)
		at org.apache.logging.log4j.LogManager.getContext(LogManager.java:196)
		at org.apache.commons.logging.LogAdapter$Log4jLog.<clinit>(LogAdapter.java:146)
		at org.apache.commons.logging.LogAdapter$Log4jAdapter.createLog(LogAdapter.java:113)
		at org.apache.commons.logging.LogAdapter.createLog(LogAdapter.java:95)
		at org.apache.commons.logging.LogFactory.getLog(LogFactory.java:67)
		at org.apache.commons.logging.LogFactory.getLog(LogFactory.java:59)
		at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:253)
		at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:102)
		at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4452)
		at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:4890)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:171)
		... 36 more

What do you advise?

Thank you!

**Comment by jmvizcainoio** [comment]
I have the same problem when i try to execute the server. Have you been find the solution ?

Thanks

**Comment by kmdauwa** [comment]
Yes, it seems to have worked for me.

I have deployed both server and DB using Docker. The server using the https://github.com/omoponfhir/omoponfhir-main-v54-r4 repo and the DB using https://github.com/SmartChartSuite/OMOP-5.4-PostgreSQL repo. Made sure that my environment variables for server are correct to connect with my DB and that both docker containers are on the same network on Docker.

Additionally in the POM.xml file of omoponfhir-r4-server subfolder, I have added the following dependencies. 

log4j-api 2.8.2
log4j-core 2.8.2

This has allowed me to see the HAPI GUI when executing the server. Still in the process of testing more.
